This is makeindex, version 2.16 [MiKTeX 22.12].
Scanning style file ./proposal.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file proposal.acn....done (18 entries accepted, 0 rejected).
Sorting entries....done (73 comparisons).
Generating output file proposal.acr....done (37 lines written, 0 warnings).
Output written in proposal.acr.
Transcript written in proposal.alg.
